name:                api
version:             0.1
github:              "zawarudo-lab/heat-project"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/api#readme>

dependencies:
- base >= 4.7 && < 5
- record-hasfield
- servant

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -F -pgmF=record-dot-preprocessor
  - -Werror=incomplete-patterns
  default-extensions:
  - LambdaCase
  - OverloadedStrings
  dependencies:
  - shared

executables:
  api:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
